### PR TITLE
iOS Working Download & Upload

### PR DESCRIPTION
**Pull request by aks3800**
1. working download speed test (iOS)
2. working upload speed test (iOS)
3. additional option of filesize (flutter)

### CODE REVIEW

**Comment by TahaMalas** [comment]
Thanks for the contribution again!

I've tried merging it on a local branch to try it, the test is completing immediately! 
Have you tried it? 

I've tried setting up the fileSize to 20,000 Bytes, which must take sometime to finish, please confirm if you're facing the same issue

**Comment by aks3800** [comment]
You are Welcome.
Yes, I have tried it and am using it in a live project.
I am not facing such issue.
Please try again using my git branch in your pubspec.yaml.
`internet_speed_test:
    git:
      url: https://github.com/aks3800/internet_speed_test
      ref: master
`

**Comment by TahaMalas** [comment]
Same issue, after one second from starting the test, the final closure gets called from both `runDownloadTest` and `runUploadTest`

**Comment by aks3800** [comment]
Did you give fileSize argument to the `startDownloadTesting` function?

Default value to this parameter is 200.

**Comment by TahaMalas** [comment]
Yes, it's the same as your commit

**Pull request merged**
